### ISSUE TITLE
[Question] how to build without running the app

### ISSUE THREAD

**Issue by HendricksonTyler** [NativeScript/nx#21]
Pretty new to this newfangled Nx workspace thing (coming from the old Angular code sharing method), so I'm trying to get my bearings in this strange land.

Is there an equivalent to running an `ns build` using this plugin? I see that there are options for `ns run`, `ns debug`, and `ns clean`, but I don't see anything for a regular build. Is this possible currently?

Running `ns build` in the NativeScript app directory seems to work fine, just wondering if there is a better Nx way to do it.

**Comment by mahmoudajawad** [comment]
Does this work for you?
```bash
npx nx run nativescript-app:build
```

I believe this should be the method to build the app (for production, without running), but it is failing for me.

**Comment by NathanWalker** [comment]
The `build` target represents the general build options. In order to build it you want to combine with the platform you want to build. For example the default workspace.json targets after adding a {N} app to Nx are as follows:
```
"build": {
      "builder": "@nativescript/nx:build",
      "options": {
        "noHmr": true,
        "production": true,
        "uglify": true,
        "release": true,
        "forDevice": true
      },
      "configurations": {
        "prod": {
          "fileReplacements": [
            {
              "replace": "./src/environments/environment.ts",
              "with": "./src/environments/environment.prod.ts"
            }
          ]
        }
      }
    },
    "ios": {
      "builder": "@nativescript/nx:build",
      "options": {
        "platform": "ios"
      },
      "configurations": {
        "prod": {
          "combineWithConfig": "build:prod"
        }
      }
    },
    "android": {
      "builder": "@nativescript/nx:build",
      "options": {
        "platform": "android"
      },
      "configurations": {
        "prod": {
          "combineWithConfig": "build:prod"
        }
      }
    },
```
As stated in readme:

> Build with an environment configuration enabled (for example, with `prod`):

**Android:**

```sh
npx nx run <app-name>:android:prod
```

**iOS:** (Mac only)

```sh
npx nx run <app-name>:ios:prod
```

When building (you are most often building a release build which the `build` target options are configured for. You can add different configurations which handle different environment files and can even add other targets with different options to use in combination with each platform target's `combineWithConfig` option.

I've updated readme to have a Heading above that section (`Create a build`) to be more clear.

Also note that there's been one webpack5 release build issue we've been working on and you may be affected by it just depending on what your app is using. We anticipate a fix for that issue within the next 2 weeks but there's a workaround solution posted in meantime:
https://github.com/NativeScript/NativeScript/issues/9358

**Comment by HendricksonTyler** [comment]
@NathanWalker thanks for your detailed explanation. Using the code above still seems to run the app, however. Looking at the `nx/packages/nx/src/builders/build/builder.ts` file, it looks like there isn't the ability to create an `ns build` using `nsOptions` currently. I've modified this file locally and have been able to add this functionality, so perhaps I'll try to find some time this weekend to create a PR for this.

**Comment by kennethkeim** [comment]
I'm running this: `npx nx run <app-name>:android:prod`
and the builder executes `ns debug` instead of `ns build`

**Comment by NathanWalker** [comment]
@kennethkeim see here: https://github.com/NativeScript/nx/issues/51 👍
